rsim/ruby-plsql

lib/plsql/jdbc_connection.rb
spec/plsql/connection_spec.rb

Whitespace reformat of jdbc_connection and connection_spec (indentations and trailing space)

Whitespace reformat jdbc_connection, connection_spec

---

lib/plsql/procedure_call.rb
spec/plsql/schema_spec.rb

Fix for the following issue: dbms_output logging didn't work properly when the database call failed with exception: it was suppressed for the failing call and was displayed with the next (successful) call.
Fixed by moving dbms output logging to the `ensure` section.

Fix dbms output in case of exception

---

Gemfile

Bumping up activerecord versions range to 4.2.x (tests are passing OK)

extend supported activerecord versions to 4.2.x

---

lib/plsql/oci_connection.rb
spec/plsql/schema_spec.rb

This is intended to resolve #46 (small fix up on top of the original proposal)
Problem occurred in multithreaded environment with shared state (class variable): OCIException: OCI8::Cursor was already closed.
* Fixed by maintaining separate stack of open cursors per thread
* Original solution by
Author:    Nikita Shilnikov
Date:      Fri Mar 1 02:31:16 2013 +0400
commit:    d363756aff95d77fd810e59383874b1289bc42a7
source:    github.com flash-gordon/ruby-plsql oci_ar_threaded_fix
* Later amended to use Thread.current in order to avoid memory leaks

Fix thread safety problem in PLSQL::OCIConnection::Cursor

---

lib/plsql/procedure_call.rb
spec/plsql/procedure_spec.rb

This includes and supersedes #50
Add support for records with boolean attributes - as input and output parameters and as return values of stored procedures.
Resolves #50

Record with booleans as params and returns

---

lib/plsql/jdbc_connection.rb
spec/plsql/procedure_spec.rb

Fix: JRuby PLS_INTEGER, BINARY_INTEGER NULL value becomes 0

---

README.md
lib/plsql/jdbc_connection.rb
lib/plsql/oci_connection.rb
lib/plsql/procedure.rb
lib/plsql/procedure_call.rb
lib/plsql/variable.rb
spec/plsql/connection_spec.rb
spec/plsql/procedure_spec.rb
spec/plsql/sql_statements_spec.rb
spec/plsql/table_spec.rb
spec/plsql/type_spec.rb
spec/plsql/variable_spec.rb

Added support for VARCHAR, SIMPLE_INTEGER, NATURAL, NATURALN, POSITIVE, POSITIVEN, SIGNTYPE datatype.
Refactored Unit Tests to use shared examples
Updated README.md

Added support for VARCHAR, SIMPLE_INTEGER+subtypes

---

lib/plsql/package.rb
spec/plsql/package_spec.rb

Ok, here we go :)
Keeping my (outdated) promise from #31 I refactored package.rb.
Best regards,
NS.

Accessing to package objects via #[]

---

lib/plsql/schema.rb
spec/plsql/package_spec.rb
spec/plsql/schema_spec.rb

We're using oracle-enhanced with schema: parameter set, so current_schema is different than the current user, which causes PL/SQL not to find available packages. current_schema should (?) be the same as session_user unless explicitly set otherwise, in which case we should use that.
I'm happy to write a specific test for this, but it'll make setup more complex since we'll need to create another user, do some grants, etc. Thoughts?

use current_schema in PLSQL::Schema#schema_name

---

lib/plsql/procedure.rb
spec/plsql/procedure_spec.rb

Now it is possible to determine if a field has default arguments.
Reciepe chef/centos-6.6 doesn't exists any more, so updated it to 6.7.
New CentOS image doesn't permit password from dictionary, so changed it
to something else.

New procedure argument metadata option 'defaulted'

---

.travis.yml
gemfiles/Gemfile.activerecord-4.1

Travis CI build matrix enables more flexibility in configuring which combinations of versions of ruby and ActiveRecord to test. In particular, it would help to skip incompatible scenarios like Rails 5.0 with ruby 1.9

Add build matrix support for Travis CI

---

.travis.yml
Gemfile
gemfiles/Gemfile.activerecord-4.2
gemfiles/Gemfile.activerecord-5.0

This pull request supports Rails 5.0 and Oracle enhanced adapter 1.7 supporting Rails 5.
I have run `rake spec` locally then most of specs are fine except for #114 which also reproduces with Rails 4.2.

Support Rails 5.0

---

.travis.yml

This pull request bumps the existing Ruby versions to the latest point release and adds JRuby 9.1.6 which is compatible with Ruby 2.3.1
```
$ ruby -v
jruby 9.1.6.0 (2.3.1) 2016-11-09 0150a76 OpenJDK 64-Bit Server VM 25.111-b16 on 1.8.0_111-b16 +jit [linux-x86_64]
```

Bump ruby versions for Travis CI testing

---

README.md
lib/plsql/jdbc_connection.rb

This pull request allows to use ojdbc7.jar when Java version is 1.7 or higher.
Refer http://www.oracle.com/technetwork/database/enterprise-edition/jdbc-faq-090281.html#01_02 for JDBC driver and JDK version matrix.

Allow ojdbc7.jar when Java version is 1.7 or higher

---

lib/plsql/schema.rb

I found the following warning in `rake spec` of [oracle-enhanced](https://github.com/rsim/oracle-enhanced).
```sh
% ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
% bundle exec rake spec
(snip)
/home/vagrant/src/ruby-plsql/lib/plsql/schema.rb:161: warning: instance variable @dbms_output_stream not initialized
```
This PR will suppress this.
I confirmed that these tests passed with local Oracle 11g environment at ruby-plsql, oracle-enhanced ([master](https://github.com/rsim/oracle-enhanced/tree/44381d397f77672939c19b4dfa5136b28429f0c3)).

Suppress `warning: instance variable @dbms_output_stream not initialized`

---

gemfiles/Gemfile.activerecord-4.1
gemfiles/Gemfile.activerecord-4.2

Some of the development dependencies for activerecord 4.x are not compatible with ruby 1.9.x - hence removing them

Remove development dependencies for CI Tests for active record 4.1 and 4.2 due to ruby 1.9.3

---

.travis.yml
gemfiles/Gemfile.activerecord-5.1

This pull request adds testing Rails 5.1.0.beta. 
JRuby 9.0.x has been excluded since Oracle enhanced adapter 1.8 will support JRuby 9.1.7.0 or higher.
Refer rsim/oracle-enhanced/pull/1147

Test Rails 5.1.0.beta

---

.travis.yml
gemfiles/Gemfile.activerecord-5.1

Rails 5.1.0.rc1 has been released. Also it bumps CRuby and JRuby version to the latest ones.

Test Rails 5.1.0.rc

---

lib/plsql/oci_connection.rb
lib/plsql/table.rb
lib/plsql/type.rb
lib/plsql/variable.rb

I found the following warnings in `rake spec` of [oracle-enhanced](https://github.com/rsim/oracle-enhanced).
```sh
% ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
% bundle exec rake
==> Loading config from ENV or use default
==> Running specs with MRI version 2.4.1
==> Effective ActiveRecord version 5.2.0.alpha
/home/vagrant/.rvm/rubies/ruby-2.4.1/bin/ruby -I/home/vagrant/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.5.4/lib:/home/vagrant/.rvm/gems/ruby-2.4.1/gems/rspec-support-3.5.0/lib /home/vagrant/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
==> Loading config from ENV or use default
==> Running specs with MRI version 2.4.1
/home/vagrant/.rvm/gems/ruby-2.4.1/bundler/gems/ruby-oci8-0ffd0c8787bd/lib/oci8/oci8.rb:627: …
```

Suppress a Ruby warnings

---

Gemfile
gemfiles/Gemfile.activerecord-5.1

Rails 5.1 and oracle enhanced adapter 1.8.0 have been released so we can now declare dependency on their final versions.

Use final version of 5.1 and oracle-enhanced 1.8.0

---

lib/plsql/schema.rb
spec/plsql/procedure_spec.rb
spec/spec_helper.rb

This builds off of @JDominator's work in #90.
With this change, ruby-plsql will still attempt to call procedures and functions even if Oracle has them in an "INVALID" status.
The "INVALID" status does not necessarily mean that the procedure has errors and cannot be called; it can also mean that an object on which it depends has been changed and the procedure needs to be recompiled.  This can happen quite frequently and would normally be a non-event except that ruby-plsql currently will not even attempt to call an invalid procedure (or a procedure in an invalid package body) and pre-emptively raises an exception.
Upon calling the invalid procedure, Oracle will implicitly attempt to recompile it.  If the recompilation fails, then a specific error will be raised.  Thus it is better to try to …

Allow calling procedures in INVALID status

---

ruby-plsql.gemspec

This PR adds license item to gemspec. This item is used as follows.
- Describing LICENSES on rubygems.org (https://rubygems.org/gems/ruby-plsql)
- List of licenses displayed by `bundle licenses` command
This will increase the opportunity for users to learn about license.

Add license to gemspec

---

Rakefile
ruby-plsql.gemspec

Follow up for #130.
The above PR did not generate ruby-plsql.gemspec with `rake gemspec`. This PR has been improved based on `rake gemspec`.

Generate a license for gemspec with `rake gemspec`

---

.travis.yml

* Ruby 2.4.3 Released
https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-4-3-released/
* Ruby 2.3.6 Released
https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-3-6-released/
* Ruby 2.2.9 Released
https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-2-9-released/
* JRuby 1.7.27 Released
http://jruby.org/2017/05/11/jruby-1-7-27
* JRuby 9.1.15.0 Released
http://jruby.org/2017/12/07/jruby-9-1-15-0

Bump ruby versions

---

.travis.yml

This pull request drops Ruby 2.1 or lower support from ruby-plsql proposed in #145

Drop CRuby 2.1 or lower support

---

.travis.yml

This pull request drops JRuby 9.0 support from ruby-plsql proposed in #145

Drop JRuby 9.0 support

---

lib/plsql/oci_connection.rb

between CRuby with ruby-oci8 and JRuby
`OCI8#describe_synonym` was implemented
to address some performance problem with `all_synonyms`
but now I do not see any performance regression due to this change.
In the very long term, when `ruby-odpi` is production ready and
ruby-plsql uses `ruby-odpi` instead of `ruby-oci8`,
it will not support `OCI8#describe_synonym`.
Refer https://github.com/kubo/ruby-odpi/issues/1#issuecomment-324360714
Even using ruby-oci8 it will use the same `PLSQL::Connection#describe_table`
for both CRuby and JRuby connections, which reduces some of code.

Avoid using `OCI8#describe_synonym` to use the same code

---

spec/plsql/procedure_spec.rb

Until further investigation made for #114
This pull request skips these 3 specs if Oracle Database version is 12c or higher.
```ruby
$ bundle exec rspec ./spec/plsql/procedure_spec.rb
.....................................................***....................................................................................................................................
Pending: (Failures listed here are expected and do not affect your suite's status)
1) Parameter type mapping / Function or procedure with XMLType parameters should process XMLType parameters
2) Parameter type mapping / Function or procedure with XMLType parameters should work when passing a NULL value
3) Parameter type mapping / Function or procedure with XMLType parameters should assign input parameter to putput parameter …
```

Skip XMLType specs if Oracle Database version is 12c or higher

---

lib/plsql/oci_connection.rb

This PR suppresses the following warning.
```console
% ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
% RUBYOPT=-w bundle exec rake
(snip)
/home/vagrant/src/ruby-plsql/lib/plsql/oci_connection.rb:298: warning:
BigDecimal.new is deprecated; use Kernel.BigDecimal method instead.
```

Suppress warning `BigDecimal.new` is deprecated

---

.travis.yml

"Ruby 2.5.1 Released"
https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-5-1-released/
"Ruby 2.4.4 Released"
https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-4-4-released/
"Ruby 2.3.7 Released"
https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-3-7-released/
"Ruby 2.2.10 Released"
https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-2-10-released/
"JRuby 9.2.0.0 Released"
http://jruby.org/2018/05/24/jruby-9-2-0-0.html

Bump Ruby versions for CI

---

.codeclimate.yml
.rubocop.yml
lib/plsql/procedure_call.rb
spec/plsql/procedure_spec.rb

This pull request bumps `TargetRubyVersion: 2.2` since ruby-plsql now only supports Rails 5.0 or higher and address RuboCop offenses.

Bump RuboCop

---

.travis.yml

* Ruby 2.5.3
https://www.ruby-lang.org/en/news/2018/10/18/ruby-2-5-3-released/
* Ruby 2.4.5
https://www.ruby-lang.org/en/news/2018/10/17/ruby-2-4-5-released/
* Ruby 2.3.8
https://www.ruby-lang.org/en/news/2018/10/17/ruby-2-3-8-released/
* JRuby 9.2.3.0
https://www.jruby.org/2018/11/09/jruby-9-2-3-0.html

Bump Ruby versions to the latest

---

.travis.yml

* Ruby 2.6.3
https://www.ruby-lang.org/en/news/2019/04/17/ruby-2-6-3-released/
* Ruby 2.5.5
https://www.ruby-lang.org/en/news/2019/03/15/ruby-2-5-5-released/
* Ruby 2.4.6
https://www.ruby-lang.org/en/news/2019/04/01/ruby-2-4-6-released/
* JRuby 9.2.7.0
https://www.jruby.org/2019/04/09/jruby-9-2-7-0.html

Bump Ruby versions at CI

---

.travis.yml
gemfiles/Gemfile.activerecord-6.0

This pull request runs CI against Rails 6.0.0.rc1. Rails 6 requires Ruby 2.5 https://github.com/rails/rails/pull/34754 then Ruby 2.4 or lower versions are excluded.

CI against Rails 6.0

---

.travis.yml

This pull request upgrades Ubuntu version to Xenial at Travis CI
https://docs.travis-ci.com/user/reference/xenial/

Use Ubuntu Xenial at Travis CI

---

.github/workflows/rubocop.yml
.rubocop.yml
Gemfile

This pull request runs RuboCop using GitHub Actions

Run RuboCop by GitHub Actions

---

lib/plsql/procedure_call.rb
lib/plsql/table.rb
spec/plsql/procedure_spec.rb
spec/plsql/table_spec.rb

intent of this PR is to make table names and params in procedures calls case-insensitive

case-insensitive table names and proc params

---

lib/plsql/connection.rb

Please use the `:oci` `driver_type` for `TruffleRuby`.  Most `ruby-oci8` tests currently pass and a related PR is submitted here:
https://github.com/kubo/ruby-oci8/pull/225

Use OCI driver type for RUBY_ENGINE TruffleRuby

---

lib/plsql/procedure.rb
spec/plsql/procedure_spec.rb

#187 
Finally, I have worked out a way to support Oracle 18c and higher. These changes were tested against Oracle 19.9 non-PDB Database and Oracle 12.1. The Oracle metadata catalogs have changed in many ways, so I have separated the implementation in new functions.
Since Oracle 19c has some strange bug with wrong database metadata entries with the test packages in the procedure specs, I have made some declaration changes which are downwards compatible. These wrong metadata entries do not show up in our application which has around 700k lines of PL/SQL code with thousands of type declarations but it seems to be a problem of the dense type declarations and type combinations used in the spec. I have not found any known Oracle issues for that but could reliably reproduce it.
For the …

Support oracle 18c

---

.travis.yml

* Ruby 3.0.2 Released
https://www.ruby-lang.org/en/news/2021/07/07/ruby-3-0-2-released/
* Ruby 2.7.4 Released
https://www.ruby-lang.org/en/news/2021/07/07/ruby-2-7-4-released/
* Ruby 2.6.8 Released
https://www.ruby-lang.org/en/news/2021/07/07/ruby-2-6-8-released/

CI against Ruby 3.0.2, 2.7.4 and 2.6.8

---

spec/support/unlock_and_setup_hr_user.sql

This statement was removed at #201 for GitHub Actions,
which is necessary for Travis CI as follows.
https://app.travis-ci.com/github/rsim/ruby-plsql/jobs/531997440
```
OCIError:
ORA-28000: the account is locked
```

Restore `alter user hr identified by hr account unlock;`

---

lib/plsql/procedure.rb

Follow up to #196.
This PR suppresses the following `assigned but unused variable` warning.
```console
==> Running specs with ruby version 3.1.0
/home/travis/.rvm/gems/ruby-head/bundler/gems/ruby-plsql-b7f469a72bd7/lib/plsql/procedure.rb:234:
warning: assigned but unused variable - object_name
==> Effective ActiveRecord version 7.0.0.alpha2
```
https://app.travis-ci.com/github/rsim/oracle-enhanced/jobs/550436965

Suppress `assigned but unused variable` warning

---

.github/workflows/rubocop.yml

```
------------------------
NOTE: This action is deprecated and is no longer maintained.
Please, migrate to https://github.com/ruby/setup-ruby, which is being actively maintained.
------------------------
```

https://github.com/actions/setup-ruby is deprecated

---

.travis.yml

* Ruby 3.1.0 Released
https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/

CI against Ruby 3.1 at Travis CI

---

lib/plsql/oci_connection.rb

This commit addresses these two failures against Rails main branch.
https://app.travis-ci.com/github/rsim/ruby-plsql/jobs/563373660
```ruby
Failures:
1) DBMS_OUTPUT logging with Activerecord connection should log output to specified stream
Failure/Error: tdo = raw_oci_connection.get_tdo_by_class(value.class)
NoMethodError:
undefined method `get_tdo_by_class' for nil:NilClass
tdo = raw_oci_connection.get_tdo_by_class(value.class)
^^^^^^^^^^^^^^^^^
2) DBMS_OUTPUT logging with Activerecord connection should log output after reconnection
Failure/Error: tdo = raw_oci_connection.get_tdo_by_class(value.class)
NoMethodError:
undefined method `get_tdo_by_class' for nil:NilClass
tdo = raw_oci_connection.get_tdo_by_class(value.class)
^^^^^^^^^^^^^^^^^
Finished in 13.12 seconds (files took 0.35468 …
```

Rename the raw connection ivar to `@raw_connection`

---

.travis.yml

* Ruby 3.1.1 Released
https://www.ruby-lang.org/en/news/2022/02/18/ruby-3-1-1-released/

CI against Ruby 3.1.1 at Travis CI #2271

---

.github/workflows/test.yml
spec/spec_helper.rb

Please add TruffleRuby to CI to track compatibility.
Since the Gemfile uses an older `1.8.2` version of `activerecord-oracle_enhanced-adapter`, I disabled those tests that rely on this gem, for TruffleRuby only, using the `NO_ACTIVERECORD` environment variable. 
```
Unsupported Ruby engine truffleruby
```

Add TruffleRuby to CI
